version: '2'
services:
    isa-app:
        image: isa
        external_links:
            - isa-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/isa?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    isa-mysql:
        extends:
            file: mysql.yml
            service: isa-mysql
